### PR TITLE
Added the best resources for learning Blockchain with hands-on experience

### PR DESCRIPTION
**Pull request by Parthmandale**
## Fixes Issue

#561 
## Changes proposed
Added three resources

## Screenshots

links

### CODE REVIEW

**Comment by Parthmandale** [comment]
@siddhant-khisty please review

**Review by siddhant-khisty — APPROVED** [review]
lgtm

**Comment by siddhant-khisty** [comment]
@Parthmandale please be patient while working in open source. Most contributors and maintainers work on these in their free time, and might be busy with other stuff as well 🙂

**Comment by Parthmandale** [comment]
@siddhant-khisty Sure will keep that in mind. Btw I just followed u on twt.

**Pull request merged**
