### PR TITLE
Added more job-boards for backend-development

### PR DESCRIPTION
**Pull request by LalitChauhan27**
## Changes proposed

- Added more job-boards for backend-development

### CODE REVIEW

**Review by siddhant-khisty — CHANGES_REQUESTED** [review]
Please include the platform name instead of `backend developer`. All the jobs in here MUST be backend

**Comment by LalitChauhan27** [comment]
Hey @siddhant-khisty, I have made the changes that you had suggested. Can you please review again?

**Review by Sandeep-RN — APPROVED** [review]
LGTM

**Review by siddhant-khisty — APPROVED** [review]
LGTM

**Pull request merged**
