### PR TITLE
Added Frontend-Development contribute Links

### PR DESCRIPTION
**Pull request by AdarshRawat1**
## Fixes Issue
N/A

## Changes proposed
Added following links to Frontend-Development contribute section.

- [OpenWISP - Website](https://github.com/openwisp/OpenWISP-Website)
-  [FreeCAD - Homepage](https://github.com/FreeCAD/FreeCAD-Homepage)

Added following links to Backend-Development contribute section.
- [openverse](https://github.com/WordPress/openverse)

### CODE REVIEW

**Comment by AnuragThePathak** [comment]
Is the openers repository more about frontend or backend?

**Comment by siddhant-khisty** [comment]
Feel free to work on this. However as Anurag pointed out, Openverse is a backend and not a frontend

**Comment by AdarshRawat1** [comment]
Noted ! @siddhant-khisty  @AnuragThePathak  
I'll remove _openverse_ from the list.

**Review by siddhant-khisty — APPROVED** [review]
lgtm

**Pull request merged**
