### PR TITLE
docs: Fix typo on CS DOJO discord link

### LINKED ISSUE #359: [Bug] Broken Community Discord link
### Description

The discord link for the CS Dojo open source community is broken. It seems to me that there is a typo in the link.

### Screenshots

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Saga-sanga**
## Fixes Issue

Closes #359

## Changes proposed
 Fixed typo on opensource community CS DOJO discord link

### CODE REVIEW

**Review by rahulpandey70 — APPROVED** [review]
LGTM

**Review by kaiwalyakoparkar — APPROVED** [review]
lgtm

**Comment by kaiwalyakoparkar** [comment]
@Saga-sanga can you please resolve the conflict so we can merge this pr :)

**Comment by siddhant-khisty** [comment]
@Saga-sanga Closing this PR as a different PR has already added the permanent link for the CS Dojo community

**Pull request closed without merging**
