### PR TITLE
Machine Learning Roadmap added

### LINKED ISSUE #314: Al and ML
### Description

if any developer is expert in ai ml can you just add a roadmap of ai ml roadmap and also good resources.

### Screenshots

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Vishvsalvi**
## Fixes Issue 
Closes #314

Added Complete Machine Learning Roadmap . All the way from Beginner level Python, Mathematics to Projects

### CODE REVIEW

**Comment by Vishvsalvi** [comment]
I need a help on this one, I've used markdownlint and it showed 0 errors.

**Comment by Vishvsalvi** [comment]
Did anyone figured out what's the problem?

**Comment by siddhant-khisty** [comment]
@Vishvsalvi you can ignore the lint error for the time being. Let us first finalize the roadmap.
cc @kaiwalyakoparkar

**Comment by Vishvsalvi** [comment]
@siddhant-khisty yeah sure have a look at it. I've added python basics, Math and every other imp resource

**Review by kaiwalyakoparkar — CHANGES_REQUESTED** [review]
I think we should have more resources under each category. Blogs, free courses etc

**Comment by Vishvsalvi** [comment]
> I think we should have more resources under each category. Blogs, free courses etc

Alright, I'll add more resources

**Comment by Vishvsalvi** [comment]
I will not add more resources in project section, since that playlist I've uploaded already consists 25+ Projects

**Comment by akshaya-hub** [comment]
@Vishvsalvi how about adding the interview questions or the job opportunities in ML

**Comment by akshaya-hub** [comment]
can I add some books to read for a few topics in ML

**Comment by Vishvsalvi** [comment]
It is a good idea but they've to be free since we are making a roadmap with free resources

**Comment by siddhant-khisty** [comment]
Closing due to inactivity

**Pull request closed without merging**
