### PR TITLE
Difference in UI Libraries across web

### PR DESCRIPTION
**Pull request by thatbeautifuldream**
## Changes proposed

- Added a resource because it is very important to understand and visualize which UI Library serves what purpose.

### CODE REVIEW

**Comment by siddhant-khisty** [comment]
This is a tier list that is highly opinion based. Not sure if we should have this.
cc @kaiwalyakoparkar

**Comment by thatbeautifuldream** [comment]
Which is why there should be a clear understanding which library serves what purpose. @siddhant-khisty

**Comment by kaiwalyakoparkar** [comment]
@thatbeautifuldream we don't need additonal heading for this. This resource can fit under some existing heading

**Review by thatbeautifuldream — COMMENTED** [review]
Added changes, please check @kaiwalyakoparkar

**Review by siddhant-khisty — APPROVED** [review]
LGTM

**Pull request merged**
