### PR TITLE
Update readme

### PR DESCRIPTION
**Pull request by KUNDAN1334**
## Changes proposed

modifying the layout as mentioned

### CODE REVIEW

**Comment by siddhant-khisty** [comment]
@KUNDAN1334 It seems that you might not have understood the requirements well. Please refer to [this message](https://github.com/WeMakeDevs/roadmaps/issues/600#issuecomment-1636028292) for how the format should be.

In the current PR you seem to have deleted the names of the resources

**Comment by AnuragNishad12** [comment]
hey bro @KUNDAN1334 why im getting this error 
photo_6179010286313388571_w
Whenever I push my changes i get this error

**Comment by KUNDAN1334** [comment]
@AnuragNishad12 It allows only maintainers to edit even i cant enable you to edit in this . i think for this you have to fork the whole repository of wemakedev.

**Comment by KUNDAN1334** [comment]
@siddhant-khisty now please have a look if still this not look better then please elaborate the changes so that i can attempt it.

**Comment by AnuragNishad12** [comment]
@KUNDAN1334 Im getting this error all over my github repository , whenever i push any changes i get this types of error and i didn't get the green marks for my changes as well 
image

**Comment by KUNDAN1334** [comment]
@AnuragNishad12 after making changes you have to merge that branch firstly in the main branch , i think you missed that part

**Comment by AnuragNishad12** [comment]
See bro @KUNDAN1334 what i did 
image

**Review by ArnavK-09 — APPROVED** [review]

**Pull request closed without merging**
