### PR TITLE
Adding Flutter development Roadmap

### LINKED ISSUE #391: Adding a Flutter Developer Roadmap
### Description

Flutter allows you to build cross-platform application with single codebase which makes it a good choice for startups and projects that cannot afford to have two different native teams for app development. 

I'd like to request to build a flutter developer roadmap or I can build one with the help of a seasoned flutter developer. :)

### Screenshots

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by TRohit20**
Adding a roadmap that allows one to go from complete novice to building applications as a Flutter Developer. 

## Fixes Issue

Closes #391 

## Changes proposed

Adding all the communities one can get involved in
Adding projects that one can contribute to and learn (Will keep updating this list)
Adding Job-boards to search and apply for jobs

## Note to Reviewers

The roadmap is not complete yet, I have begun to build it piece by piece and will finish it soon enough. I'am opening this PR so the maintainers can also keep a track of changes and work in order to avoid the issue from going stale. Thank you.

### CODE REVIEW

**Review by siddhant-khisty — CHANGES_REQUESTED** [review]
Hey, you seem to have created a new folder for a Flutter-Roadmap. Please include these communities in the Android Development roadmap itself.

**Comment by TRohit20** [comment]
Sure, I will create an issue regarding it now and open a PR resolving the same so it doesn't collide with this Flutter dev roadmap PR

**Review by siddhant-khisty — CHANGES_REQUESTED** [review]
Hey this directory called as `Flutter-Development` doesn't exist in the main repo. Please move this to the `Android-Development` directory. 

I saw a different PR as well that committed to this directory. Not sure how this directory is getting created.

**Comment by TRohit20** [comment]
@siddhant-khisty , Umm, I am not sure I got your point, The other PR was adding communities to Android development, But this PR is completely different as this is where I am building the flutter roadmap. Maybe I got it wrong, LMK?

**Comment by siddhant-khisty** [comment]
@TRohit20 Oh my bad. I was referring to this PR itself. Please mark this as a Draft PR, that way I'll know it's a WIP

**Comment by TRohit20** [comment]
Was just going to. Done.

**Comment by PranavMasekar** [comment]
Hey @TRohit20 @siddhant-khisty  Flutter roadmap is not added yet , So is this PR is under development or whats the status?? bcz I also wanted to add some points in flutter roadmap but it was not yet added to repository.

**Review by kunal-kushwaha — APPROVED** [review]

**Pull request merged**
