### PR TITLE
Machine Learning roadmap

### LINKED ISSUE #314: Al and ML
### Description

if any developer is expert in ai ml can you just add a roadmap of ai ml roadmap and also good resources.

### Screenshots

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Vishvsalvi**
`Closes #314`
## Screenshots

image

## Note to reviewers

This is the 2nd time I'm making this roadmap. You closed this issue few weeks ago due to inactivity from your side.
This time I'm requesting you to give some attention for this new roadmap.

### CODE REVIEW

**Review by Sandeep-RN — CHANGES_REQUESTED** [review]
Link is not working in Projects for
"Top 50 Machine Learning Projects Ideas for Beginners - ProjectPro (projectpro.io)"
Screenshot 2023-03-15 133232

**Comment by Vishvsalvi** [comment]
Thankyou, I'll fix this.

**Comment by Vishvsalvi** [comment]
> Link is not working in Projects for "Top 50 Machine Learning Projects Ideas for Beginners - ProjectPro (projectpro.io)" Screenshot 2023-03-15 133232

It is working, can you ask some one else to check on their system

image

**Comment by Sandeep-RN** [comment]
> > Link is not working in Projects for "Top 50 Machine Learning Projects Ideas for Beginners - ProjectPro (projectpro.io)" Screenshot 2023-03-15 133232
> 
> It is working, can you ask some one else to check on their system
> 
> image

Oh ya, It's working now👍,
Maby the website was down when i was checking it. 

We can merge this👍.

**Review by Sandeep-RN — APPROVED** [review]
LGTM 
Can be merged.

**Comment by Vishvsalvi** [comment]
Can you help me with the Lint code base error I used lint extentsion but it did not point out any error.

**Comment by Sandeep-RN** [comment]
> Can you help me with the Lint code base error I used lint extentsion but it did not point out any error.

I think you can ignore that,
You only need an approval for a member with write access.

**Comment by Vishvsalvi** [comment]
> 

Okk thankyou very much

**Comment by Vishvsalvi** [comment]
@Sandeep-RN can you inform the reviewers or the maintainer to have a look at this commit. It's a request.

**Comment by Sandeep-RN** [comment]
@siddhant-khisty or @kaiwalyakoparkar Can you please take care of this.

**Comment by Vishvsalvi** [comment]
@siddhant-khisty please have a look at this pr

**Pull request closed without merging**
