### PR TITLE
Updated README.md - added Solidity, EVM Resource

### PR DESCRIPTION
**Pull request by prathamesh2525**
Added Link to -> Solidity, Ethereum Virtual Machine, Hardhat, ethers.js, Damn Vulnerable Defi Part1 and Part 2

### CODE REVIEW

**Comment by siddhant-khisty** [comment]
I'm not sure if this should be added as it seems to be covering too many different technologies.

**Comment by prathamesh2525** [comment]
It covers Solidity and EVM in depth by step by step through documentation, other topics can be optional to opt out not.

**Comment by siddhant-khisty** [comment]
@prathamesh2525 Please think about it from a totally newbie's perspective. Giving them tons of technologies all at once is going to confuse them a lot rather than making them understand. Please feel free to open a PR with individual resources instead of a all-in-one

**Comment by prathamesh2525** [comment]
Yeah I totally agree with you. Maybe It can be added to the intermediate level.

**Pull request closed without merging**
