### PR TITLE
Added more Frontend projects you can contribute

### PR DESCRIPTION
**Pull request by soumil1**
## Fixes Issue
#584

## Changes proposed
<li><a href="https://github.com/gatsbyjs/gatsby">Gatsby</a></li>
<li><a href="https://github.com/twbs/bootstrap">Twbs Bootstrap</a></li>

### CODE REVIEW

**Comment by soumil1** [comment]
https://github.com/WeMakeDevs/roadmaps/issues/584#issue-1783780442

**Review by sergeivassiljev — APPROVED** [review]
looks ok

**Comment by AnuragThePathak** [comment]
I think your commit has some problem, so Git is unable to detect the existing lines properly. It may be helpful if you can add the new stuff in description as well.

**Comment by siddhant-khisty** [comment]
Hey, @soumil1 it seems you might have edited all the existing resources as well. We are unable to figure out which ones were added by you. Either recreate a branch and re-commit the changes and open a new PR or you can mention the resources which you have added

**Comment by soumil1** [comment]
> Hey, @soumil1 it seems you might have edited all the existing resources as well. We are unable to figure out which ones were added by you. Either recreate a branch and re-commit the changes and open a new PR or you can mention the resources which you have added

Hey, @siddhant-khisty sorry from my end. Actually, on the first line, I mistakenly changed "## - 2nd level heading" to "# - 1st level" on Open Source Frontend projects to which you can contribute, which made it appear as if I had changed the entire Readme, but I haven't. I only added the "Gatsby" and "Twbs Bootstrap" links

**Comment by soumil1** [comment]
> I think your commit has some problem, so Git is unable to detect the existing lines properly. It may be helpful if you can add the new stuff in description as well.

Can I mention the new changes I made to the description now?

**Comment by soumil1** [comment]
> > > I think your commit has some problem, so Git is unable to detect the existing lines properly. It may be helpful if you can add the new stuff in description as well.
> > 
> > 
> > Can I mention the new changes I made to the description now?
> 
> Yes

Edited the description. Can you please check

**Comment by siddhant-khisty** [comment]
Hey, @soumil1 these projects that you've included do not really fit under the frontend category. Imo they would be better suited as backend projects. Yes they are frontend frameworks, but a contributor would need a good amount of frontend as well as backend knowledge to contribute to them. I could be wrong tho. @AnuragThePathak @kaiwalyakoparkar what are your opinions on this issue?

**Comment by AnuragThePathak** [comment]
Bootstrap one is frontend ig and Gatsby too (but these are not web apps, except the Bootstrap website).

**Comment by soumil1** [comment]
So what do I do now? @siddhant-khisty @AnuragThePathak  
Can I create a new pull request and update both of these links in backend development?

**Comment by siddhant-khisty** [comment]
@soumil1 The bootstrap is one fine I guess. But please move the gatsby one to backend. You can simply push more commits to this branch to update this PR as well

**Review by siddhant-khisty — APPROVED** [review]
lgtm

**Comment by siddhant-khisty** [comment]
@soumil1 please fix the merge conflicts and we can merge

**Comment by soumil1** [comment]
Sorry for causing a problem. I accidentally force-pushed the commit instead of deleting the conflicts. Is there any way to recover from this disaster :(
@siddhant-khisty

**Comment by AnuragThePathak** [comment]
Do you still have the commits with you? If yes we can recover from the disaster.

**Pull request closed without merging**
