### PR TITLE
Addes some useful resources.

### PR DESCRIPTION
**Pull request by rahulpandey70**
Added some useful resources of database (PostgresSql, MySql and MongoDb).

### CODE REVIEW

**Comment by siddhant-khisty** [comment]
Hey @rahulpandey70, please remove the MySQL resources. While it's a great piece of technology, having folks learn multiple SQL databases like MySQL, postgress, etc would make them confused as to which one to actually learn. imo the Postgress resources should be enough.

**Comment by rahulpandey70** [comment]
@siddhant-khisty, I think this should be the folks decision, what they wanted to learn. Or if you want I'll remove MySql resource.

**Comment by siddhant-khisty** [comment]
@rahulpandey70 I agree with that point. But you must take into consideration the fact that most folks using the roadmaps are beginners. Giving them too many technologies that do the same thing will confuse them. Please remove the MySQL section.

**Comment by rahulpandey70** [comment]
Ok, I'm removing MySQL resource.

**Pull request merged**
