### PR TITLE
Added a complete golang playlist

### PR DESCRIPTION
**Pull request by tarunclub**

### CODE REVIEW

**Review by Sandeep-RN — APPROVED** [review]
LGTM

**Comment by tarunclub** [comment]
@Sandeep-RN do we need another approval?

**Comment by Sandeep-RN** [comment]
> @Sandeep-RN do we need another approval?

Ya, this needs an approval from a member with write access to merge.

**Comment by Sandeep-RN** [comment]
> @Sandeep-RN do we need another approval?

Ya, this needs an approval from a member with write access to merge.

**Review by siddhant-khisty — APPROVED** [review]

**Pull request merged**
