### PR TITLE
Added More Open Source Projects!!

### PR DESCRIPTION
**Pull request by ni5arga**
Hello! I have added some opensource projects! 

The projects shared here are 100% opensource and are accepting contributions!

I have added some projects by Hackclub like Spirg, Sinerider & Some Assembly Required as well as some other famous opensource projects!

### CODE REVIEW

**Review by kaiwalyakoparkar — APPROVED** [review]
lgtm

**Comment by ni5arga** [comment]
Don't merge, I am adding more @kaiwalyakoparkar

**Comment by kaiwalyakoparkar** [comment]
> Please don't merge, I am adding more @kaiwalyakoparkar

Please create draft pr for such cases

**Comment by ni5arga** [comment]
> > Please don't merge, I am adding more @kaiwalyakoparkar
> 
> Please create draft pr for such cases

Sorry, I will from next time. I've completed this PR.

**Review by kaiwalyakoparkar — APPROVED** [review]

**Pull request merged**
